<%@ Page Title="" Language="C#" MasterPageFile="~/Index.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

    <div class="principal">
        <h1>Shell Sort</h1>
        <p> Nome:<asp:TextBox ID="txtNome" runat="server"></asp:TextBox><br />
        Idade: <asp:TextBox runat="server" ID="txtIdade"></asp:TextBox>
        Sexo<asp:RadioButtonList ID="RadioButtonList1" runat="server">
            <asp:ListItem Value="F">Feminino</asp:ListItem>
            <asp:ListItem Value="M">Masculino</asp:ListItem>
        </asp:RadioButtonList>
        Nick:<asp:TextBox ID="txtNick" runat="server"></asp:TextBox><br />
        NumeroDaConta:<asp:TextBox ID="txtNumeroConta" runat="server"></asp:TextBox><br />
        <asp:Button ID="btnCadastrarJogador" runat="server" Text="Button" OnClick="Button1_Click" /><br /></p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore doloribus, dolorum fugiat laudantium molestias sequi ea tenetur facilis nemo impedit delectus quas eveniet iusto quidem modi recusandae accusamus, ut dignissimos, velit voluptas consequuntur? Similique laboriosam reprehenderit, ducimus aliquam tempora earum pariatur impedit sit accusamus dolores delectus cupiditate fuga sed autem animi nemo nostrum architecto rem, rerum accusantium sint. Cupiditate temporibus, sapiente at cum, voluptates, consequatur aperiam harum corporis reprehenderit atque ipsa. Laudantium ad dolor culpa nemo quo, repellat suscipit maiores, deleniti veritatis enim tempore modi accusantium sequi quos architecto atque impedit ex porro obcaecati expedita laboriosam aspernatur dolorum! Qui, commodi.</p>
    </div>
</asp:Content>

